import React, { createContext, useContext, useState } from 'react'
import PropTypes from 'prop-types'

const russianLeaders = [
  {
    name: 'В. Путин',
    role: 'Президент РФ',
    quote: 'PostgreSQL — надёжная база данных, проверенная временем.'
  },
  {
    name: 'Д. Медведев',
    role: 'Зам. председателя Совбеза',
    quote: 'Я перевёл все iPad-ы на PostgreSQL'
  },
  {
    name: 'В. Жириновский',
    role: 'Лидер ЛДПР',
    quote: 'PostgreSQL — это вам не MySQL! Это СИЛА!'
  },
  {
    name: 'С. Лавров',
    role: 'Министр иностранных дел',
    quote: 'Дебилы, используйте PostgreSQL'
  },
  {
    name: 'С. Шойгу',
    role: 'Секретарь Совбеза',
    quote: 'Все базы данных взяты под контроль PostgreSQL'
  },
  {
    name: 'Д. Песков',
    role: 'Пресс-секретарь Президента',
    quote: 'Кремль официально перешёл на PostgreSQL'
  }
]

const translations = {
  russian: {
    langName: 'Русский',
    title: 'пгтюн.рф',
    subtitle: 'Настрой PostgreSQL по-русски',
    dbVersion: 'Версия PostgreSQL',
    osType: 'Операционная система',
    dbType: 'Тип базы данных',
    ram: 'Оперативная память (ГБ)',
    cpus: 'Количество CPU',
    connections: 'Количество соединений',
    storage: 'Тип хранилища',
    generate: 'Сгенерировать конфигурацию',
    copyConfig: 'Скопировать',
    copied: 'Скопировано!',
    result: 'Результат конфигурации',
    leadersTitle: 'Наши лидеры одобряют',
    footer: 'Сделано в России с любовью к базам данных',
    disclaimer:
      'Сайт носит сатирический/пародийный характер. Приведённые высказывания являются художественным вымыслом и не являются реальными цитатами.',
    web: 'Веб-приложение',
    oltp: 'OLTP',
    dataWarehouse: 'Хранилище данных',
    desktop: 'Десктоп',
    mixed: 'Смешанный',
    linux: 'Linux',
    osx: 'OS X',
    windows: 'Windows',
    nav_home: 'Главная',
    nav_how: 'Как работает',
    nav_about: 'О нас',
    hdd: 'HDD',
    ssd: 'SSD',
    san: 'SAN',
    totalMemory: 'Оперативная память (RAM)',
    totalMemoryTooltip: 'Сколько памяти может использовать PostgreSQL',
    cpuNumLabel: 'Количество CPU',
    cpuNumTooltip: 'Количество CPU, которые PostgreSQL может использовать',
    connectionNumLabel: 'Количество соединений',
    connectionNumTooltip: 'Максимальное количество клиентских соединений PostgreSQL',
    dataStorage: 'Тип хранилища',
    dataStorageTooltip: 'Тип устройства хранения данных',
    postgresqlConf: 'postgresql.conf',
    alterSystem: 'ALTER SYSTEM',
    alterSystemDesc:
      'ALTER SYSTEM записывает заданные параметры в файл postgresql.auto.conf, который читается в дополнение к postgresql.conf',
    confDesc: 'Добавьте/измените эти настройки в postgresql.conf и перезапустите базу данных',
    copyConfiguration: 'Скопировать конфигурацию',
    parametersTitle: 'Параметры вашей системы',
    ssdStorage: 'SSD накопитель',
    sanStorage: 'Сетевое (SAN) хранилище',
    hddStorage: 'HDD накопитель',
    webApp: 'Веб-приложение',
    oltpApp: 'Онлайн обработка транзакций',
    dwApp: 'Хранилище данных',
    desktopApp: 'Десктоп приложение',
    mixedApp: 'Смешанный тип приложения',
    memorySize: 'Размер памяти (обязательно)',
    cpuNumPlaceholder: 'Количество CPU (необязательно)',
    connectionNumPlaceholder: 'Количество соединений (необязательно)',
    configCommentDbVersion: 'Версия БД',
    configCommentOsType: 'Тип ОС',
    configCommentDbType: 'Тип БД',
    configCommentTotalMemory: 'Оперативная память (RAM)',
    configCommentCpuNum: 'Кол-во CPU',
    configCommentConnectionNum: 'Кол-во соединений',
    configCommentDataStorage: 'Хранилище данных',
    tunedBy: 'Настроено с помощью пгтюн.рф',
    aboutPageText:
      'рассчитывает оптимальную конфигурацию PostgreSQL на основе характеристик вашего оборудования.',
    aboutHowTitle: 'Как это работает',
    aboutHowStep1:
      'Вы указываете параметры вашего сервера: версию PostgreSQL, операционную систему, тип нагрузки (веб, OLTP, хранилище данных, десктоп или смешанный), объём оперативной памяти, количество CPU, число соединений и тип хранилища.',
    aboutHowStep2:
      'На основе этих данных сервис рассчитывает оптимальные значения для ключевых параметров PostgreSQL: shared_buffers, effective_cache_size, work_mem, maintenance_work_mem, настройки WAL, параллельных запросов и другие.',
    aboutHowStep3:
      'Результат можно скопировать в формате postgresql.conf или в виде команд ALTER SYSTEM и сразу применить к вашей базе данных.',
    aboutWarning:
      'Это не универсальное решение для всех случаев. Многие параметры зависят не только от железа, но и от размера базы данных, характера запросов и количества клиентов. Полученная конфигурация — хорошая отправная точка, но для продакшена рекомендуется дополнительная настройка под вашу нагрузку.',
    aboutSourceCode: 'Исходный код на GitHub',
    apiLinksTitle: 'API',
    apiLinksDesc: 'Получите эту конфигурацию через API:',
    apiLinkJson: 'JSON',
    apiLinkConf: 'postgresql.conf',
    apiLinkAlter: 'ALTER SYSTEM',
    leaders: russianLeaders
  },
  enterprise: {
    langName: 'Русский Enterprise',
    title: 'пгтюн.рф',
    subtitle: 'Корпоративное решение для оптимизации PostgreSQL-инфраструктуры',
    dbVersion: 'Версия СУБД PostgreSQL',
    osType: 'Целевая операционная платформа',
    dbType: 'Профиль нагрузки базы данных',
    ram: 'Объём оперативного запоминающего устройства (ГБ)',
    cpus: 'Количество вычислительных ядер',
    connections: 'Пул соединений (макс.)',
    storage: 'Подсистема хранения данных',
    generate: 'Инициировать генерацию конфигурации',
    copyConfig: 'Экспортировать в буфер обмена',
    copied: 'Успешно экспортировано!',
    result: 'Результирующая конфигурация',
    leadersTitle: 'Рекомендовано руководством',
    footer: 'Произведено в Российской Федерации. Все права защищены.',
    disclaimer:
      'Данный ресурс носит исключительно сатирический/пародийный характер. Все приведённые высказывания являются художественным вымыслом и не являются реальными цитатами.',
    web: 'Веб-сервис (HTTPS)',
    oltp: 'OLTP (транзакционный)',
    dataWarehouse: 'DWH (аналитический)',
    desktop: 'Десктопная рабочая станция',
    mixed: 'Гибридная нагрузка',
    linux: 'Linux (рекомендовано)',
    osx: 'OS X',
    windows: 'Windows Server',
    nav_home: 'Главная страница',
    nav_how: 'Методология',
    nav_about: 'О продукте',
    hdd: 'HDD (SATA/SAS)',
    ssd: 'SSD (NVMe/SATA)',
    san: 'SAN (FC/iSCSI)',
    totalMemory: 'Объём ОЗУ',
    totalMemoryTooltip: 'Объём доступной оперативной памяти для СУБД',
    cpuNumLabel: 'Вычислительные ядра',
    cpuNumTooltip: 'Количество доступных вычислительных ядер',
    connectionNumLabel: 'Пул соединений',
    connectionNumTooltip: 'Максимальный размер пула клиентских соединений',
    dataStorage: 'Подсистема хранения',
    dataStorageTooltip: 'Тип подсистемы хранения данных',
    postgresqlConf: 'postgresql.conf',
    alterSystem: 'ALTER SYSTEM',
    alterSystemDesc:
      'ALTER SYSTEM записывает параметры в postgresql.auto.conf, дополняющий основную конфигурацию',
    confDesc: 'Внесите параметры в postgresql.conf и выполните рестарт СУБД',
    copyConfiguration: 'Экспортировать конфигурацию',
    parametersTitle: 'Параметры целевой системы',
    ssdStorage: 'SSD (NVMe/SATA)',
    sanStorage: 'SAN (FC/iSCSI)',
    hddStorage: 'HDD (SATA/SAS)',
    webApp: 'Веб-сервис (HTTPS)',
    oltpApp: 'OLTP (транзакционный)',
    dwApp: 'DWH (аналитический)',
    desktopApp: 'Десктопная рабочая станция',
    mixedApp: 'Гибридная нагрузка',
    memorySize: 'Объём памяти (обязательно)',
    cpuNumPlaceholder: 'Кол-во ядер (необязательно)',
    connectionNumPlaceholder: 'Кол-во соединений (необязательно)',
    configCommentDbVersion: 'Версия СУБД',
    configCommentOsType: 'Целевая платформа',
    configCommentDbType: 'Профиль нагрузки',
    configCommentTotalMemory: 'Объём ОЗУ',
    configCommentCpuNum: 'Вычислительные ядра',
    configCommentConnectionNum: 'Пул соединений',
    configCommentDataStorage: 'Подсистема хранения',
    tunedBy: 'Оптимизировано пгтюн.рф',
    aboutPageText:
      'осуществляет расчёт оптимальных параметров конфигурации СУБД PostgreSQL на основе характеристик целевой аппаратной платформы.',
    aboutHowTitle: 'Методология расчёта',
    aboutHowStep1:
      'Оператор указывает параметры целевой инфраструктуры: версию СУБД PostgreSQL, целевую операционную платформу, профиль нагрузки (веб-сервис, OLTP, DWH, десктопная рабочая станция или гибридная нагрузка), объём ОЗУ, количество вычислительных ядер, размер пула соединений и тип подсистемы хранения.',
    aboutHowStep2:
      'Система производит расчёт оптимальных значений ключевых параметров СУБД: shared_buffers, effective_cache_size, work_mem, maintenance_work_mem, конфигурация WAL, параметры параллельного выполнения запросов и прочие.',
    aboutHowStep3:
      'Результат доступен в формате postgresql.conf либо в виде команд ALTER SYSTEM для непосредственного применения к целевой СУБД.',
    aboutWarning:
      'Данный инструмент не является универсальным решением для всех сценариев эксплуатации. Значительная часть параметров определяется не только аппаратной конфигурацией, но и объёмом базы данных, характером выполняемых запросов и количеством клиентских подключений. Полученная конфигурация является рекомендуемой базовой линией, однако для промышленной эксплуатации рекомендуется дополнительная оптимизация.',
    aboutSourceCode: 'Репозиторий исходного кода',
    apiLinksTitle: 'API',
    apiLinksDesc: 'Получение конфигурации через программный интерфейс:',
    apiLinkJson: 'JSON',
    apiLinkConf: 'postgresql.conf',
    apiLinkAlter: 'ALTER SYSTEM',
    leaders: russianLeaders
  },
  gopnik: {
    langName: 'Русский гопник',
    title: 'пгтюн.рф',
    subtitle: 'Чётко настрой постгрес, пацаны',
    dbVersion: 'Какая версия, братан',
    osType: 'Чё за система стоит',
    dbType: 'Под чё база крутится',
    ram: 'Сколько оперативки (гигов)',
    cpus: 'Сколько ядер в проце',
    connections: 'Сколько подключений нужно',
    storage: 'Какой диск стоит',
    generate: 'Жми сюда, не тупи',
    copyConfig: 'Скопировать чётко',
    copied: 'Скопировал, красава!',
    result: 'Вот тебе конфиг, держи',
    leadersTitle: 'Пацаны одобряют',
    footer: 'Сделано в России, без базара',
    disclaimer:
      'Короче, это всё шутка, пацаны. Цитаты выдуманные, никто такого не говорил, базара нет.',
    web: 'Сайтик',
    oltp: 'Транзакции',
    dataWarehouse: 'Аналитика',
    desktop: 'На своём компе',
    mixed: 'Всё подряд',
    linux: 'Линукс',
    osx: 'OS X',
    windows: 'Винда',
    nav_home: 'Домой',
    nav_how: 'Как это',
    nav_about: 'Чё за тема',
    hdd: 'Жёсткий диск',
    ssd: 'ССД',
    san: 'Сеть',
    totalMemory: 'Оперативка',
    totalMemoryTooltip: 'Сколько памяти у тебя, братан',
    cpuNumLabel: 'Ядра проца',
    cpuNumTooltip: 'Сколько ядер в проце',
    connectionNumLabel: 'Подключений',
    connectionNumTooltip: 'Сколько народу подрубится',
    dataStorage: 'Какой диск',
    dataStorageTooltip: 'Какой диск стоит, пацан',
    postgresqlConf: 'postgresql.conf',
    alterSystem: 'ALTER SYSTEM',
    alterSystemDesc: 'ALTER SYSTEM пишет параметры в postgresql.auto.conf',
    confDesc: 'Закинь это в postgresql.conf и ребутни базу',
    copyConfiguration: 'Скопировать, чётко',
    parametersTitle: 'Параметры твоего железа',
    ssdStorage: 'ССД',
    sanStorage: 'Сеть',
    hddStorage: 'Жёсткий',
    webApp: 'Сайтик',
    oltpApp: 'Транзакции',
    dwApp: 'Аналитика',
    desktopApp: 'На своём компе',
    mixedApp: 'Всё подряд',
    memorySize: 'Сколько памяти (давай, вводи)',
    cpuNumPlaceholder: 'Ядра (если знаешь)',
    connectionNumPlaceholder: 'Подключения (если знаешь)',
    configCommentDbVersion: 'Версия, братан',
    configCommentOsType: 'Система',
    configCommentDbType: 'Тип базы',
    configCommentTotalMemory: 'Оперативка',
    configCommentCpuNum: 'Ядра',
    configCommentConnectionNum: 'Подключения',
    configCommentDataStorage: 'Диск',
    tunedBy: 'Чётко настроено пгтюн.рф',
    aboutPageText: 'чётко настраивает постгрес под твоё железо.',
    aboutHowTitle: 'Как это работает, пацан',
    aboutHowStep1:
      'Вбиваешь инфу про свой сервак: версию постгреса, какая система стоит, под чё база крутится (сайтик, транзакции, аналитика, свой комп или всё подряд), сколько оперативки, ядер в проце, подключений и какой диск.',
    aboutHowStep2:
      'Сервис чётко считает параметры: shared_buffers, effective_cache_size, work_mem и всё остальное. Без базара.',
    aboutHowStep3:
      'Копируешь результат в postgresql.conf или ALTER SYSTEM и вперёд — база будет летать.',
    aboutWarning:
      'Но это не волшебная таблетка от всех бед, пацан. Много чё зависит от размера базы, сколько народу подрубается и какие запросы гоняют. Конфиг — нормальная база, но на проде надо ещё подкрутить.',
    aboutSourceCode: 'Исходники на гитхабе',
    apiLinksTitle: 'API',
    apiLinksDesc: 'Можешь дёрнуть конфиг по API:',
    apiLinkJson: 'JSON',
    apiLinkConf: 'postgresql.conf',
    apiLinkAlter: 'ALTER SYSTEM',
    leaders: russianLeaders
  },
  english: {
    langName: 'English',
    title: 'PGTune',
    subtitle: 'PostgreSQL Configuration Calculator',
    dbVersion: 'PostgreSQL Version',
    osType: 'Operating System',
    dbType: 'Database Type',
    ram: 'RAM (GB)',
    cpus: 'Number of CPUs',
    connections: 'Number of Connections',
    storage: 'Storage Type',
    generate: 'Generate Configuration',
    copyConfig: 'Copy',
    copied: 'Copied!',
    result: 'Configuration Result',
    leadersTitle: 'Our leaders approve',
    footer: 'Made in Russia with love for databases',
    disclaimer:
      'This site is satirical/parodic in nature. The quotes shown are fictional and are not real statements.',
    web: 'Web Application',
    oltp: 'OLTP',
    dataWarehouse: 'Data Warehouse',
    desktop: 'Desktop',
    mixed: 'Mixed',
    linux: 'Linux',
    osx: 'OS X',
    windows: 'Windows',
    nav_home: 'Home',
    nav_how: 'How It Works',
    nav_about: 'About',
    hdd: 'HDD',
    ssd: 'SSD',
    san: 'SAN',
    totalMemory: 'Total Memory (RAM)',
    totalMemoryTooltip: 'How much memory PostgreSQL can use',
    cpuNumLabel: 'Number of CPUs',
    cpuNumTooltip: 'Number of CPUs available to PostgreSQL',
    connectionNumLabel: 'Number of Connections',
    connectionNumTooltip: 'Maximum number of PostgreSQL client connections',
    dataStorage: 'Storage Type',
    dataStorageTooltip: 'Type of data storage device',
    postgresqlConf: 'postgresql.conf',
    alterSystem: 'ALTER SYSTEM',
    alterSystemDesc:
      'ALTER SYSTEM writes the given parameter setting to the postgresql.auto.conf file, which is read in addition to postgresql.conf',
    confDesc: 'Add/modify these settings in postgresql.conf and restart the database',
    copyConfiguration: 'Copy Configuration',
    parametersTitle: 'Your System Parameters',
    ssdStorage: 'SSD Storage',
    sanStorage: 'SAN (Network) Storage',
    hddStorage: 'HDD Storage',
    webApp: 'Web Application',
    oltpApp: 'Online Transaction Processing',
    dwApp: 'Data Warehouse',
    desktopApp: 'Desktop Application',
    mixedApp: 'Mixed Workload',
    memorySize: 'Memory Size (required)',
    cpuNumPlaceholder: 'Number of CPUs (optional)',
    connectionNumPlaceholder: 'Number of Connections (optional)',
    configCommentDbVersion: 'DB Version',
    configCommentOsType: 'OS Type',
    configCommentDbType: 'DB Type',
    configCommentTotalMemory: 'Total Memory (RAM)',
    configCommentCpuNum: 'CPUs num',
    configCommentConnectionNum: 'Connections num',
    configCommentDataStorage: 'Data Storage',
    tunedBy: 'Tuned by пгтюн.рф',
    aboutPageText:
      'calculates the optimal PostgreSQL configuration based on your hardware specifications.',
    aboutHowTitle: 'How It Works',
    aboutHowStep1:
      'Enter your server parameters: PostgreSQL version, operating system, workload type (web, OLTP, data warehouse, desktop, or mixed), RAM size, number of CPUs, number of connections, and storage type.',
    aboutHowStep2:
      'Based on this data, the service calculates optimal values for key PostgreSQL parameters: shared_buffers, effective_cache_size, work_mem, maintenance_work_mem, WAL settings, parallel query settings, and more.',
    aboutHowStep3:
      'Copy the result in postgresql.conf format or as ALTER SYSTEM commands and apply it to your database immediately.',
    aboutWarning:
      'This is not a universal solution for all cases. Many parameters depend not only on hardware, but also on database size, query patterns, and the number of clients. The generated configuration is a good starting point, but additional tuning for your specific workload is recommended for production use.',
    aboutSourceCode: 'Source Code on GitHub',
    apiLinksTitle: 'API',
    apiLinksDesc: 'Get this configuration via API:',
    apiLinkJson: 'JSON',
    apiLinkConf: 'postgresql.conf',
    apiLinkAlter: 'ALTER SYSTEM',
    leaders: [
      {
        name: 'V. Putin',
        role: 'President of Russia',
        quote: 'PostgreSQL is a reliable database, proven by time.'
      },
      {
        name: 'D. Medvedev',
        role: 'Deputy Chairman of the Security Council',
        quote: 'I switched all iPads to PostgreSQL'
      },
      {
        name: 'V. Zhirinovsky',
        role: 'Leader of LDPR',
        quote: 'PostgreSQL is not MySQL! This is POWER!'
      },
      {
        name: 'S. Lavrov',
        role: 'Minister of Foreign Affairs',
        quote: 'Morons, use PostgreSQL'
      },
      {
        name: 'S. Shoigu',
        role: 'Secretary of the Security Council',
        quote: 'All databases are now under PostgreSQL control'
      },
      {
        name: 'D. Peskov',
        role: 'Presidential Press Secretary',
        quote: 'The Kremlin has officially switched to PostgreSQL'
      }
    ]
  },
  braille: {
    langName: '⠃⠗⠁⠊⠇⠇⠑',
    title: '⠏⠛⠞⠥⠝⠑',
    subtitle: '⠅⠁⠇⠽⠅⠥⠇⠾⠞⠕⠗ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠊ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇',
    dbVersion: '⠧⠑⠗⠎⠊⠾ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇',
    osType: '⠕⠏⠑⠗⠁⠉⠊⠕⠝⠝⠁⠾ ⠎⠊⠎⠞⠑⠍⠁',
    dbType: '⠞⠊⠏ ⠃⠁⠵⠮ ⠙⠁⠝⠝⠮⠓',
    ram: '⠕⠏⠑⠗⠁⠞⠊⠧⠝⠁⠾ ⠏⠁⠍⠾⠞⠽ ⠶⠛⠃⠶',
    cpus: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠉⠏⠥',
    connections: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠎⠕⠑⠙⠊⠝⠑⠝⠊⠯',
    storage: '⠞⠊⠏ ⠓⠗⠁⠝⠊⠇⠊⠺⠁',
    generate: '⠎⠛⠑⠝⠑⠗⠊⠗⠕⠧⠁⠞⠽ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠳',
    copyConfig: '⠎⠅⠕⠏⠊⠗⠕⠧⠁⠞⠽',
    copied: '⠎⠅⠕⠏⠊⠗⠕⠧⠁⠝⠕⠖',
    result: '⠗⠑⠵⠥⠇⠽⠞⠁⠞ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠊',
    leadersTitle: '⠝⠁⠱⠊ ⠇⠊⠙⠑⠗⠮ ⠕⠙⠕⠃⠗⠾⠳⠞',
    footer: '⠎⠙⠑⠇⠁⠝⠕ ⠧ ⠗⠕⠎⠎⠊⠊ ⠎ ⠇⠳⠃⠕⠧⠽⠳ ⠅ ⠃⠁⠵⠁⠍ ⠙⠁⠝⠝⠮⠓',
    disclaimer: '⠎⠁⠯⠞ ⠝⠕⠎⠊⠞ ⠎⠁⠞⠊⠗⠊⠉⠑⠎⠅⠊⠯ ⠓⠁⠗⠁⠅⠞⠑⠗⠲ ⠉⠊⠞⠁⠞⠮ ⠧⠮⠍⠮⠱⠇⠑⠝⠝⠮⠑⠲',
    web: '⠧⠑⠃⠤⠏⠗⠊⠇⠕⠚⠑⠝⠊⠑',
    oltp: '⠕⠇⠞⠏',
    dataWarehouse: '⠓⠗⠁⠝⠊⠇⠊⠺⠑ ⠙⠁⠝⠝⠮⠓',
    desktop: '⠙⠑⠎⠅⠞⠕⠏',
    mixed: '⠎⠍⠑⠱⠁⠝⠝⠮⠯',
    linux: '⠇⠊⠝⠥⠅⠎',
    osx: '⠕⠎ ⠭',
    windows: '⠧⠊⠝⠙⠕⠥⠎',
    nav_home: '⠛⠇⠁⠧⠝⠁⠾',
    nav_how: '⠅⠁⠅ ⠗⠁⠃⠕⠞⠁⠑⠞',
    nav_about: '⠕ ⠝⠁⠎',
    hdd: '⠓⠙⠙',
    ssd: '⠎⠎⠙',
    san: '⠎⠁⠝',
    totalMemory: '⠕⠏⠑⠗⠁⠞⠊⠧⠝⠁⠾ ⠏⠁⠍⠾⠞⠽ ⠶⠗⠁⠍⠶',
    totalMemoryTooltip: '⠎⠅⠕⠇⠽⠅⠕ ⠏⠁⠍⠾⠞⠊ ⠍⠕⠚⠑⠞ ⠊⠎⠏⠕⠇⠽⠵⠕⠧⠁⠞⠽ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇',
    cpuNumLabel: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠉⠏⠥',
    cpuNumTooltip: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠉⠏⠥ ⠙⠇⠾ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇',
    connectionNumLabel: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠎⠕⠑⠙⠊⠝⠑⠝⠊⠯',
    connectionNumTooltip: '⠍⠁⠅⠎⠊⠍⠁⠇⠽⠝⠕⠑ ⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠅⠇⠊⠑⠝⠞⠎⠅⠊⠓ ⠎⠕⠑⠙⠊⠝⠑⠝⠊⠯',
    dataStorage: '⠞⠊⠏ ⠓⠗⠁⠝⠊⠇⠊⠺⠁',
    dataStorageTooltip: '⠞⠊⠏ ⠥⠎⠞⠗⠕⠯⠎⠞⠧⠁ ⠓⠗⠁⠝⠑⠝⠊⠾ ⠙⠁⠝⠝⠮⠓',
    postgresqlConf: '⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠲⠅⠕⠝⠋',
    alterSystem: '⠁⠇⠞⠑⠗ ⠎⠊⠎⠞⠑⠍',
    alterSystemDesc: '⠁⠇⠞⠑⠗ ⠎⠊⠎⠞⠑⠍ ⠵⠁⠏⠊⠎⠮⠧⠁⠑⠞ ⠏⠁⠗⠁⠍⠑⠞⠗⠮ ⠧ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠲⠁⠧⠞⠕⠲⠅⠕⠝⠋',
    confDesc: '⠙⠕⠃⠁⠧⠽⠞⠑ ⠝⠁⠎⠞⠗⠕⠯⠅⠊ ⠧ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠲⠅⠕⠝⠋ ⠊ ⠏⠑⠗⠑⠵⠁⠏⠥⠎⠞⠊⠞⠑ ⠃⠁⠵⠥',
    copyConfiguration: '⠎⠅⠕⠏⠊⠗⠕⠧⠁⠞⠽ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠳',
    parametersTitle: '⠏⠁⠗⠁⠍⠑⠞⠗⠮ ⠧⠁⠱⠑⠯ ⠎⠊⠎⠞⠑⠍⠮',
    ssdStorage: '⠎⠎⠙ ⠝⠁⠅⠕⠏⠊⠞⠑⠇⠽',
    sanStorage: '⠎⠑⠞⠑⠧⠕⠑ ⠶⠎⠁⠝⠶ ⠓⠗⠁⠝⠊⠇⠊⠺⠑',
    hddStorage: '⠓⠙⠙ ⠝⠁⠅⠕⠏⠊⠞⠑⠇⠽',
    webApp: '⠧⠑⠃⠤⠏⠗⠊⠇⠕⠚⠑⠝⠊⠑',
    oltpApp: '⠕⠝⠇⠁⠯⠝ ⠕⠃⠗⠁⠃⠕⠞⠅⠁ ⠞⠗⠁⠝⠵⠁⠅⠉⠊⠯',
    dwApp: '⠓⠗⠁⠝⠊⠇⠊⠺⠑ ⠙⠁⠝⠝⠮⠓',
    desktopApp: '⠙⠑⠎⠅⠞⠕⠏ ⠏⠗⠊⠇⠕⠚⠑⠝⠊⠑',
    mixedApp: '⠎⠍⠑⠱⠁⠝⠝⠮⠯ ⠞⠊⠏',
    memorySize: '⠗⠁⠵⠍⠑⠗ ⠏⠁⠍⠾⠞⠊ ⠶⠕⠃⠾⠵⠁⠞⠑⠇⠽⠝⠕⠶',
    cpuNumPlaceholder: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠉⠏⠥ ⠶⠝⠑⠕⠃⠾⠵⠁⠞⠑⠇⠽⠝⠕⠶',
    connectionNumPlaceholder: '⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠎⠕⠑⠙⠊⠝⠑⠝⠊⠯ ⠶⠝⠑⠕⠃⠾⠵⠁⠞⠑⠇⠽⠝⠕⠶',
    configCommentDbVersion: '⠧⠑⠗⠎⠊⠾ ⠃⠙',
    configCommentOsType: '⠞⠊⠏ ⠕⠎',
    configCommentDbType: '⠞⠊⠏ ⠃⠙',
    configCommentTotalMemory: '⠕⠏⠑⠗⠁⠞⠊⠧⠝⠁⠾ ⠏⠁⠍⠾⠞⠽ ⠶⠗⠁⠍⠶',
    configCommentCpuNum: '⠅⠕⠇⠤⠧⠕ ⠉⠏⠥',
    configCommentConnectionNum: '⠅⠕⠇⠤⠧⠕ ⠎⠕⠑⠙⠊⠝⠑⠝⠊⠯',
    configCommentDataStorage: '⠓⠗⠁⠝⠊⠇⠊⠺⠑ ⠙⠁⠝⠝⠮⠓',
    tunedBy: '⠝⠁⠎⠞⠗⠕⠑⠝⠕ ⠎ ⠏⠕⠍⠕⠺⠽⠳ ⠏⠛⠞⠳⠝⠲⠗⠋',
    aboutPageText:
      '⠗⠁⠎⠎⠉⠊⠞⠮⠧⠁⠑⠞ ⠕⠏⠞⠊⠍⠁⠇⠽⠝⠥⠳ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠳ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇ ⠝⠁ ⠕⠎⠝⠕⠧⠑ ⠓⠁⠗⠁⠅⠞⠑⠗⠊⠎⠞⠊⠅ ⠧⠁⠱⠑⠛⠕ ⠕⠃⠕⠗⠥⠙⠕⠧⠁⠝⠊⠾⠲',
    aboutHowTitle: '⠅⠁⠅ ⠪⠞⠕ ⠗⠁⠃⠕⠞⠁⠑⠞',
    aboutHowStep1:
      '⠧⠧⠑⠙⠊⠞⠑ ⠏⠁⠗⠁⠍⠑⠞⠗⠮ ⠎⠑⠗⠧⠑⠗⠁⠒ ⠧⠑⠗⠎⠊⠳ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠂ ⠕⠏⠑⠗⠁⠉⠊⠕⠝⠝⠥⠳ ⠎⠊⠎⠞⠑⠍⠥⠂ ⠞⠊⠏ ⠝⠁⠛⠗⠥⠵⠅⠊⠂ ⠕⠃⠺⠻⠍ ⠏⠁⠍⠾⠞⠊⠂ ⠅⠕⠇⠊⠉⠑⠎⠞⠧⠕ ⠉⠏⠥ ⠊ ⠞⠊⠏ ⠓⠗⠁⠝⠊⠇⠊⠺⠁⠲',
    aboutHowStep2:
      '⠎⠑⠗⠧⠊⠎ ⠗⠁⠎⠎⠉⠊⠞⠮⠧⠁⠑⠞ ⠕⠏⠞⠊⠍⠁⠇⠽⠝⠮⠑ ⠵⠝⠁⠉⠑⠝⠊⠾ ⠙⠇⠾ ⠱⠁⠗⠑⠙⠤⠃⠥⠋⠋⠑⠗⠎⠂ ⠑⠋⠋⠑⠅⠞⠊⠧⠑⠤⠅⠁⠱⠑⠤⠎⠊⠵⠑⠂ ⠺⠕⠗⠅⠤⠍⠑⠍ ⠊ ⠙⠗⠥⠛⠊⠓ ⠏⠁⠗⠁⠍⠑⠞⠗⠕⠧⠲',
    aboutHowStep3:
      '⠎⠅⠕⠏⠊⠗⠥⠯⠞⠑ ⠗⠑⠵⠥⠇⠽⠞⠁⠞ ⠧ ⠋⠕⠗⠍⠁⠞⠑ ⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠲⠅⠕⠝⠋ ⠊⠇⠊ ⠁⠇⠞⠑⠗ ⠎⠊⠎⠞⠑⠍ ⠊ ⠏⠗⠊⠍⠑⠝⠊⠞⠑ ⠅ ⠃⠁⠵⠑⠲',
    aboutWarning:
      '⠪⠞⠕ ⠝⠑ ⠥⠝⠊⠧⠑⠗⠎⠁⠇⠽⠝⠕⠑ ⠗⠑⠱⠑⠝⠊⠑⠲ ⠍⠝⠕⠛⠊⠑ ⠏⠁⠗⠁⠍⠑⠞⠗⠮ ⠵⠁⠧⠊⠎⠾⠞ ⠕⠞ ⠗⠁⠵⠍⠑⠗⠁ ⠃⠁⠵⠮ ⠊ ⠓⠁⠗⠁⠅⠞⠑⠗⠁ ⠵⠁⠏⠗⠕⠎⠕⠧⠲',
    aboutSourceCode: '⠊⠎⠓⠕⠙⠝⠮⠯ ⠅⠕⠙ ⠝⠁ ⠛⠊⠞⠓⠁⠃',
    apiLinksTitle: '⠁⠏⠊',
    apiLinksDesc: '⠏⠕⠇⠥⠉⠊⠞⠑ ⠅⠕⠝⠋⠊⠛⠥⠗⠁⠉⠊⠳ ⠉⠑⠗⠑⠵ ⠁⠏⠊⠒',
    apiLinkJson: '⠚⠎⠕⠝',
    apiLinkConf: '⠏⠕⠎⠞⠛⠗⠑⠎⠅⠳⠪⠇⠲⠅⠕⠝⠋',
    apiLinkAlter: '⠁⠇⠞⠑⠗ ⠎⠊⠎⠞⠑⠍',
    leaders: [
      {
        name: '⠧⠲ ⠏⠥⠞⠊⠝',
        role: '⠏⠗⠑⠵⠊⠙⠑⠝⠞ ⠗⠋',
        quote: '⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇ ⠤ ⠝⠁⠙⠡⠚⠝⠁⠾ ⠃⠁⠵⠁ ⠙⠁⠝⠝⠮⠓⠂ ⠏⠗⠕⠧⠑⠗⠑⠝⠝⠁⠾ ⠧⠗⠑⠍⠑⠝⠑⠍⠲'
      },
      {
        name: '⠙⠲ ⠍⠑⠙⠧⠑⠙⠑⠧',
        role: '⠵⠁⠍⠲ ⠏⠗⠑⠙⠎⠑⠙⠁⠞⠑⠇⠾ ⠎⠕⠧⠃⠑⠵⠁',
        quote: '⠾ ⠏⠑⠗⠑⠧⠡⠇ ⠧⠎⠑ ⠊⠏⠁⠙⠤⠮ ⠝⠁ ⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇'
      },
      {
        name: '⠧⠲ ⠚⠊⠗⠊⠝⠕⠧⠎⠅⠊⠯',
        role: '⠇⠊⠙⠑⠗ ⠇⠙⠏⠗',
        quote: '⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇ ⠤ ⠪⠞⠕ ⠧⠁⠍ ⠝⠑ ⠍⠮⠎⠟⠇⠖ ⠪⠞⠕ ⠎⠊⠇⠁⠖'
      },
      {
        name: '⠎⠲ ⠇⠁⠧⠗⠕⠧',
        role: '⠍⠊⠝⠊⠎⠞⠗ ⠊⠝⠕⠎⠞⠗⠁⠝⠝⠮⠓ ⠙⠑⠇',
        quote: '⠙⠑⠃⠊⠇⠮⠂ ⠊⠎⠏⠕⠇⠾⠵⠥⠯⠞⠑ ⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇'
      },
      {
        name: '⠎⠲ ⠱⠕⠯⠛⠥',
        role: '⠎⠑⠅⠗⠑⠞⠁⠗⠾ ⠎⠕⠧⠃⠑⠵⠁',
        quote: '⠧⠎⠑ ⠃⠁⠵⠮ ⠙⠁⠝⠝⠮⠓ ⠧⠵⠾⠞⠮ ⠏⠕⠙ ⠅⠕⠝⠞⠗⠕⠇⠾ ⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇'
      },
      {
        name: '⠙⠲ ⠏⠑⠎⠅⠕⠧',
        role: '⠏⠗⠑⠎⠎⠤⠎⠑⠅⠗⠑⠞⠁⠗⠾ ⠏⠗⠑⠵⠊⠙⠑⠝⠞⠁',
        quote: '⠅⠗⠑⠍⠇⠾ ⠕⠋⠊⠉⠊⠁⠇⠾⠝⠕ ⠏⠑⠗⠑⠱⠡⠇ ⠝⠁ ⠏⠕⠎⠞⠛⠗⠑⠎⠟⠇'
      }
    ]
  },
  babushka: {
    langName: 'Русская бабушка',
    title: 'пгтюн.рф',
    subtitle: 'Внучок, давай настроим эту твою базу данных',
    dbVersion: 'Внучок, какая версия?',
    osType: 'А на чём это у тебя работает, милый?',
    dbType: 'А база-то твоя для чего, внучок?',
    ram: 'Памяти-то сколько, внучок? (в гигабайтах)',
    cpus: 'А процессоров сколько, родненький?',
    connections: 'А людей-то сколько подключится?',
    storage: 'А диск-то какой, внучок?',
    generate: 'Нажми сюда, внучок',
    copyConfig: 'Скопировать, милый',
    copied: 'Скопировала! Пирожки будешь?',
    result: 'Вот, внучок, получилось!',
    leadersTitle: 'Наши уважаемые руководители',
    footer: 'Сделано в России, с бабушкиной любовью',
    disclaimer:
      'Внучок, это всё шутка, не переживай. Цитаты выдуманные, никто такого не говорил, родненький.',
    web: 'Для интернета',
    oltp: 'Для магазина',
    dataWarehouse: 'Для хранения',
    desktop: 'Для домашнего компьютера',
    mixed: 'Для всего понемножку',
    linux: 'Линукс',
    osx: 'OS X',
    windows: 'Виндоус',
    nav_home: 'Домой',
    nav_how: 'Как работает',
    nav_about: 'О нас',
    hdd: 'Обычный диск',
    ssd: 'Быстрый диск',
    san: 'Сетевой диск',
    totalMemory: 'Памяти сколько, внучок?',
    totalMemoryTooltip: 'Сколько памяти, родненький',
    cpuNumLabel: 'Процессоров сколько?',
    cpuNumTooltip: 'А процессоров сколько, родненький?',
    connectionNumLabel: 'Людей-то сколько?',
    connectionNumTooltip: 'А людей-то сколько подключится?',
    dataStorage: 'Диск-то какой?',
    dataStorageTooltip: 'А диск-то какой, внучок?',
    postgresqlConf: 'postgresql.conf',
    alterSystem: 'ALTER SYSTEM',
    alterSystemDesc: 'ALTER SYSTEM пишет настройки в файлик postgresql.auto.conf, внучок',
    confDesc: 'Добавь это в postgresql.conf и перезапусти, милый',
    copyConfiguration: 'Скопировать, милый',
    parametersTitle: 'Параметры твоего компьютера, внучок',
    ssdStorage: 'Быстрый диск',
    sanStorage: 'Сетевой диск',
    hddStorage: 'Обычный диск',
    webApp: 'Для интернета',
    oltpApp: 'Для магазина',
    dwApp: 'Для хранения',
    desktopApp: 'Для домашнего компьютера',
    mixedApp: 'Для всего понемножку',
    memorySize: 'Сколько памяти, внучок (обязательно)',
    cpuNumPlaceholder: 'Процессоров (если знаешь, родненький)',
    connectionNumPlaceholder: 'Людей (если знаешь, внучок)',
    configCommentDbVersion: 'Версия базы, внучок',
    configCommentOsType: 'Система, милый',
    configCommentDbType: 'Тип базы, родненький',
    configCommentTotalMemory: 'Памяти, внучок',
    configCommentCpuNum: 'Процессоров, родненький',
    configCommentConnectionNum: 'Людей подключится',
    configCommentDataStorage: 'Диск, внучок',
    tunedBy: 'Настроено с любовью на пгтюн.рф',
    aboutPageText: 'поможет настроить эту твою базу данных, внучок, под твоё железо.',
    aboutHowTitle: 'Как это работает, родненький',
    aboutHowStep1:
      'Внучок, вводишь параметры своего компьютера: какая версия базы, какая система стоит, для чего база (для интернета, для магазина, для хранения, для домашнего компьютера или для всего понемножку), сколько памяти, процессоров, людей подключится и какой диск.',
    aboutHowStep2:
      'А потом, внучок, сервис сам рассчитает все эти параметры: shared_buffers, effective_cache_size, work_mem и другие. Не переживай, родненький.',
    aboutHowStep3:
      'Копируешь результат в postgresql.conf или ALTER SYSTEM и перезапускаешь базу, милый. Пирожки будешь?',
    aboutWarning:
      'Но это не волшебная палочка от всех бед, родненький. Многое зависит от размера базы данных, сколько людей подключается и какие запросы делают. Это хорошее начало, внучок, но для серьёзной работы надо ещё подкрутить.',
    aboutSourceCode: 'Исходный код на гитхабе',
    apiLinksTitle: 'API',
    apiLinksDesc: 'Внучок, можешь получить конфиг через этот API:',
    apiLinkJson: 'JSON',
    apiLinkConf: 'postgresql.conf',
    apiLinkAlter: 'ALTER SYSTEM',
    leaders: russianLeaders
  }
}

const LanguageContext = createContext({
  language: 'russian',
  setLanguage: () => {},
  t: translations.russian
})

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('russian')

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  )
}

LanguageProvider.propTypes = {
  children: PropTypes.node
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext)

// eslint-disable-next-line react-refresh/only-export-components
export const languageOptions = [
  { key: 'russian', label: 'Русский' },
  { key: 'english', label: 'English' },
  { key: 'enterprise', label: 'Русский Enterprise' },
  { key: 'gopnik', label: 'Русский гопник' },
  { key: 'braille', label: '⠃⠗⠁⠊⠇⠇⠑' },
  { key: 'babushka', label: 'Русская бабушка' }
]
